spring:
  application:
    name: spring-keycloak-demo
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://198.19.249.128:18080/realms/ws-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://198.19.249.128:18080/realms/ws-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-keycloak-demo
            client-secret: rt7gOc1jYLw7GJAMoBpL2qHTa43BMnkl
            scope: openid
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081

logging:
  level:
    org.springframework.security: TRACE