###
POST {{ keycloak-host }}/realms/demo-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=spring-keycloak-demo&client_secret=BGUTdLu0cLHOU7LItqVxV9068yEQjoMC&username=p.gaponenko&password=password&grant_type=password

###
GET {{ app-host }}/authenticated.html
Authorization: {{ token }}
###
GET {{ app-host }}/manager.html
Authorization: {{ token }}


